swagger: '2.0'

#################################INFO START##########################
info:
  description: |
    成绩查询服务API
  version: 1.0.0
  title: Grade Service
#  termsOfService: http://swagger.io/terms/
  contact:
    email: 3480437308@qq.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
###############################INFO END#################################

host: ccnubux.muxixyz.com
basePath: /api/
schemes:
 - https
 - http
######################TAG START#######################################
# tags:
# - name: auth
  # description: 学而鉴权


##########################TAG END######################################

###########################AUTH START#################################




########################PATH START####################################
paths:
  /grade/:
    get:
      summary: 总成绩查询
      description: 学校网站改版，请求方式有一些变化
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: query
        name: xnm
        description: 学年，例如请求2017-2018学年成绩，则xnm=2017
        required: true
      - in: query
        name: xqm
        description: 学期，第一学期 xqm=3, 第二学期 xqm=12, 第三学期 xqm=16
        required: true
      - in: header
        name: Bigipserverpool
        description: 模拟登录用
        required: true
      - in: header
        name: Sid
        description: 学号
        required: true
      - in: header
        name: Jsessionid
        description: 模拟登录用
        required:
      - in: header
        name: Authorization
        description: "Basic Base64(sid:pwd)"
        required: true
      responses:
        401:
          description: 未授权
        403:
          description: 禁止访问
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                course:
                  type: string
                credit:
                  type: string
                grade:
                  type: integer
                category:
                  type: string
                type:
                  type: string
                jxb_id:
                  type: integer
                kcxzmc:
                  type: string
                ending:
                  type: integer
                usual:
                  type: integer
  /grade/another/:
    get:
      summary: 获取缓存的成绩数据
      description: 学校网站改版，请求方式有一些变化
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: query
        name: xnm
        description: 学年，例如请求2017-2018学年成绩，则xnm=2017
        required: true
      - in: query
        name: xqm
        description: 学期，第一学期 xqm=3, 第二学期 xqm=12, 第三学期 xqm=16
        required: true
      - in: header
        name: Sid
        description: 学号
        required: true
      responses:
        401:
          description: 未授权
        403:
          description: 禁止访问
        404:
          description: 缓存中没有数据
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                course:
                  type: string
                credit:
                  type: string
                grade:
                  type: integer
                category:
                  type: string
                type:
                  type: string
                jxb_id:
                  type: integer
                kcxzmc:
                  type: string
                ending:
                  type: integer
                usual:
                  type: integer


